packages:
  - .

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "@firebase/util"
  - "protobufjs"
  - "sharp"
  - "workerd"
  - "agent-browser"
  - "electron"
  - "electron-winstaller"

blockExoticSubdeps: true

minimumReleaseAge: 4320

allowBuilds:
  '@firebase/util': true
  '@swc/core': true
  agent-browser: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true