/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PanelSlugRouteImport } from './routes/panel/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiKeysAccountRouteImport } from './routes/api/keys/account'
import { Route as ApiKeysCheckRouteImport } from './routes/api/keys/check'
import { Route as ApiKeysMachineRouteImport } from './routes/api/keys/machine'
import { Route as ApiWebhooksFacebookRouteImport } from './routes/api/webhooks/facebook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelSlugRoute = PanelSlugRouteImport.update({
  id: '/panel/$slug',
  path: '/panel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysAccountRoute = ApiKeysAccountRouteImport.update({
  id: '/api/keys/account',
  path: '/api/keys/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysCheckRoute = ApiKeysCheckRouteImport.update({
  id: '/api/keys/check',
  path: '/api/keys/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysMachineRoute = ApiKeysMachineRouteImport.update({
  id: '/api/keys/machine',
  path: '/api/keys/machine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksFacebookRoute = ApiWebhooksFacebookRouteImport.update({
  id: '/api/webhooks/facebook',
  path: '/api/webhooks/facebook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel/$slug': typeof PanelSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/keys/account': typeof ApiKeysAccountRoute
  '/api/keys/check': typeof ApiKeysCheckRoute
  '/api/keys/machine': typeof ApiKeysMachineRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel/$slug': typeof PanelSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/keys/account': typeof ApiKeysAccountRoute
  '/api/keys/check': typeof ApiKeysCheckRoute
  '/api/keys/machine': typeof ApiKeysMachineRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel/$slug': typeof PanelSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/keys/account': typeof ApiKeysAccountRoute
  '/api/keys/check': typeof ApiKeysCheckRoute
  '/api/keys/machine': typeof ApiKeysMachineRoute
  '/api/webhooks/facebook': typeof ApiWebhooksFacebookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/panel/$slug'
    | '/api/auth/$'
    | '/api/keys/account'
    | '/api/keys/check'
    | '/api/keys/machine'
    | '/api/webhooks/facebook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/panel/$slug'
    | '/api/auth/$'
    | '/api/keys/account'
    | '/api/keys/check'
    | '/api/keys/machine'
    | '/api/webhooks/facebook'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/panel/$slug'
    | '/api/auth/$'
    | '/api/keys/account'
    | '/api/keys/check'
    | '/api/keys/machine'
    | '/api/webhooks/facebook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PanelSlugRoute: typeof PanelSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiKeysAccountRoute: typeof ApiKeysAccountRoute
  ApiKeysCheckRoute: typeof ApiKeysCheckRoute
  ApiKeysMachineRoute: typeof ApiKeysMachineRoute
  ApiWebhooksFacebookRoute: typeof ApiWebhooksFacebookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/$slug': {
      id: '/panel/$slug'
      path: '/panel/$slug'
      fullPath: '/panel/$slug'
      preLoaderRoute: typeof PanelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/account': {
      id: '/api/keys/account'
      path: '/api/keys/account'
      fullPath: '/api/keys/account'
      preLoaderRoute: typeof ApiKeysAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/check': {
      id: '/api/keys/check'
      path: '/api/keys/check'
      fullPath: '/api/keys/check'
      preLoaderRoute: typeof ApiKeysCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys/machine': {
      id: '/api/keys/machine'
      path: '/api/keys/machine'
      fullPath: '/api/keys/machine'
      preLoaderRoute: typeof ApiKeysMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/facebook': {
      id: '/api/webhooks/facebook'
      path: '/api/webhooks/facebook'
      fullPath: '/api/webhooks/facebook'
      preLoaderRoute: typeof ApiWebhooksFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PanelSlugRoute: PanelSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiKeysAccountRoute: ApiKeysAccountRoute,
  ApiKeysCheckRoute: ApiKeysCheckRoute,
  ApiKeysMachineRoute: ApiKeysMachineRoute,
  ApiWebhooksFacebookRoute: ApiWebhooksFacebookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
